set -s escape-time 0
set -g base-index 1

set -g history-limit 50000

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set-option -g focus-events on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
