#!/bin/sh

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super+Shift Return spawn foot

riverctl map normal Super+Shift B spawn firefox-bin

# Super+Shift+C to close the focused view
riverctl map normal Super+Shift C close

# Super+Shift+Q to exit river
riverctl map normal Super+Shift Q exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+I and Super+D to increment/decrement the main count of rivertile(1)
riverctl map normal Super I send-layout-cmd rivertile "main-count +1"
riverctl map normal Super D send-layout-cmd rivertile "main-count -1"

# Super+Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super+Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super+Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Shift+Space to toggle float
riverctl map normal Super+Shift Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

riverctl map normal None XF86AudioRaiseVolume spawn 'wpctl set-volume @DEFAULT_SINK@ 5%+ --limit 1.0'
riverctl map normal None XF86AudioLowerVolume spawn 'wpctl set-volume @DEFAULT_SINK@ 5%-'
riverctl map normal None XF86AudioMute spawn 'wpctl set-mute @DEFAULT_SINK@ toggle'

# Control screen backlight brightness
riverctl map normal None XF86MonBrightnessDown spawn 'xbacklight -dec 5'
riverctl map normal None XF86MonBrightnessUp spawn 'xbacklight -inc 5'

# Set background and border color
riverctl background-color 0x1f1f28
riverctl border-color-focused 0x2d4f67
riverctl border-color-unfocused 0x252535

riverctl xcursor-theme Adwaita 16

# Set keyboard repeat rate
riverctl set-repeat 50 300

riverctl keyboard-layout -variant colemak us

riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad tap enabled
riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad natural-scroll enabled

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-location left -main-count 1 -main-ratio 0.5 &

riverctl spawn gentoo-pipewire-launcher
riverctl spawn kanshi
# riverctl spawn waybar
# riverctl spawn 'wlsunset -l 40 -L -79'
